---
- hosts: all
  become: true  # Using 'true' is the standard way to denote Boolean values in YAML

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400  

    - name: Installing Basic Tools
      apt:
        name:
          - git
          - vim
          - nano
          - net-tools
          - mlocate
          - zip
          - unzip
          - htop
          - curl
          - tmux
          - openssh-server
          - wget
          - cmake
        state: present
