---
- name: Install multiple Go tools and run pdtm
  hosts: dev
  become: no  # Go install typically does not require elevated privileges
  vars:
    go_bin_path: "/usr/local/bin"  # Correct path to the Go binary
    go_packages:
      - "github.com/projectdiscovery/pdtm/cmd/pdtm@latest"
      - "github.com/owasp-amass/amass/v4/...@master"
  tasks:
    # - name: Install Go packages
    #   ansible.builtin.command:
    #     cmd: "{{ go_bin_path }}/go install -v {{ item }}"
    #   environment:
    #     GOPATH: "{{ ansible_env.HOME }}/go"
    #     GOBIN: "{{ ansible_env.HOME }}/go/bin"
    #     PATH: "{{ ansible_env.PATH }}:{{ go_bin_path }}"
    #   loop: "{{ go_packages }}"
    #   ignore_errors: yes  # Continue on errors, adjust as needed

    # - name: Run pdtm -install-all
    #   ansible.builtin.shell:
    #     cmd: "{{ ansible_env.HOME }}/go/bin/pdtm -install-all"
    #   environment:
    #     PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/go/bin"

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400  

    - name: Install required packages
      become: yes  # This will instruct Ansible to use sudo for the tasks
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - git
          - vim
          - nano
          - net-tools
          - mlocate
          - zip
          - unzip
          - htop
          - curl
          - tmux
          - openssh-server
          - wget
          - cmake
          - libpcap-dev
          - nmap
          - cewl
          - jq
          - build-essential
          - software-properties-common
          - python3
          - python3-pip
          - openssl
      register: install_packages
      until: install_packages is succeeded


    - name: Clone SecLists repository
      ansible.builtin.git:
        repo: 'https://github.com/danielmiessler/SecLists.git'
        dest: '/opt/SecLists'
        depth: 1

    - name: Download findomain
      ansible.builtin.get_url:
        url: 'https://github.com/findomain/findomain/releases/latest/download/findomain-linux-i386.zip'
        dest: '/tmp/findomain-linux-i386.zip'

    - name: Unzip findomain
      ansible.builtin.unarchive:
        src: '/tmp/findomain-linux-i386.zip'
        dest: '/tmp/'
        remote_src: yes
        creates: '/tmp/findomain'

    - name: Set execute permission on findomain
      ansible.builtin.file:
        path: '/tmp/findomain'
        mode: '0755'

    - name: Move findomain to /usr/bin/
      ansible.builtin.command:
        cmd: 'mv /tmp/findomain /usr/bin/findomain'

    - name: Remove the findomain zip file
      ansible.builtin.file:
        path: '/tmp/findomain-linux-i386.zip'
        state: absent

    - name: Install pip packages
      ansible.builtin.pip:
        name: "{{ item }}"
        state: latest
      loop:
        - arjun
        - wfuzz
