---
- name: Install and configure pdtm using Go
  hosts: dev
  become: yes  # You may not need 'become' for the go install command
  vars:
    go_package: "github.com/projectdiscovery/pdtm/cmd/pdtm@latest"
    go_bin_path: "/usr/local/go/bin"  # Adjust if you have a custom location for Go binaries

  tasks:
    - name: Install pdtm using go install
      ansible.builtin.command:
        cmd: "{{ go_bin_path }}/go install -v {{ go_package }}"
        environment:
          PATH: "{{ ansible_env.PATH }}:{{ go_bin_path }}"
          GOPATH: "{{ ansible_env.HOME }}/go"
          GOBIN: "{{ ansible_env.HOME }}/go/bin"
      become_user: "{{ ansible_env.USER }}"
      ignore_errors: yes  # If go is not installed, this will allow the playbook to continue

    - name: Run pdtm -install-all to install all dependencies
      ansible.builtin.command:
        cmd: "{{ ansible_env.HOME }}/go/bin/pdtm -install-all"
      become_user: "{{ ansible_env.USER }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/go/bin"
