---
- name: Install Go 1.19
  hosts: dev
  become: yes
  vars:
    go_version: "1.19"
    go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
    go_download_url: "https://go.dev/dl/{{ go_tarball }}"

  tasks:
    - name: Download the Go tarball
      ansible.builtin.get_url:
        url: "{{ go_download_url }}"
        dest: "/tmp/{{ go_tarball }}"
        timeout: 60
        force: true

    - name: Remove existing Go installation
      ansible.builtin.file:
        path: /usr/local/go
        state: absent

    - name: Extract Go tarball
      ansible.builtin.unarchive:
        src: "/tmp/{{ go_tarball }}"
        dest: /usr/local
        extra_opts: [--strip-components=1]
        creates: /usr/local/go/bin/go

    - name: Set Go environment variables for all users
      ansible.builtin.blockinfile:
        path: /etc/profile.d/go.sh
        block: |
          export PATH=$PATH:/usr/local/go/bin
          export PATH=$PATH:{{ ansible_env.HOME }}/go/bin
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK for Go environment variables"

    - name: Check Go version
      ansible.builtin.command: go version
      register: go_version_output

    - name: Show Go version output
      ansible.builtin.debug:
        msg: "{{ go_version_output.stdout }}"
