---
- name: Update and upgrade all Ubuntu servers
  hosts: dev
  become: yes
  tasks:
    - name: Ensure the apt cache is updated
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Cache is considered valid for 1 hour

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: yes

    - name: Remove unnecessary packages and dependencies
      ansible.builtin.apt:
        autoremove: yes
        purge: yes

    - name: Clean up the apt cache
      ansible.builtin.apt:
        autoclean: yes

    - name: Reboot the machine if needed
      ansible.builtin.reboot:
        msg: "Rebooting for system updates"
        reboot_timeout: 600 # 10 minutes timeout for the reboot
