---
- name: Create a new system user with SSH access
  hosts: template
  become: yes  # Use sudo for privilege escalation
  vars:
    username: semaphore  # Define the username variable
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDnv02isSZibtBMTqyA+MlBh7nqSLjpKFQiSCK5THVHQqurobuuDZM0Yn5l5vCJRVMEFTdbaenP4zhASWwA96lw2z55iUxQND9BaMnvUdyZt/N9H/LqEk5Gz89AaDvsQNORDlYK1cGpAMbEOTCzGKv/BJo0r3rwCqAcgG7K9Oifl9RYi3BRrjH8tZUcwEwkmktAN5ol/6paMbgTB0KrJmuLM/M/cqJ4DyAVP4qyFtIw2zOCX47/SSvABlr12+u2kqWLYTliSY4ARXClEas5JN7tB6IJTSzSWaH0bAa4EVHzFqLXASkEKpHVsId62K958FykAz0MGuPEIN1VTDPnPRHzF8u2nsou74713ITHJvNx2nwtrB6pH1v0SLMhegYD6xqZhIa4sQllpv6PlAsX8eF/1rTe564NlBZ5CXsETEZ+v070d/AtEbbKMp9OFUsUgnhlOtMeyU+IZ37aoFf7w9YeD1AdCTSqUTO04XQstd2WOu/OBK0JvPd+FX2mIncryhc= semaphore@5cd6c0bba89f"  # Define the public key variable

  tasks:
    - name: Create a new user with a home directory and bash shell
      ansible.builtin.user:
        name: "{{ username }}"
        comment: "Ansible Managed User"
        shell: /bin/bash
        create_home: yes
        home: "/home/{{ username }}"

    - name: Set up .ssh directory for the user
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Add authorized_keys for the user
      ansible.builtin.copy:
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        content: "{{ ssh_public_key }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Allow the user to have passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%{{ username }}'
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'

    - name: Ensure the user can use sudo without a password
      ansible.builtin.user:
        name: "{{ username }}"
        append: yes
        groups: sudo
        system: no
