---
- hosts: master
  become: yes
  tasks:
    # Ensure pip is installed (needed to install Docker SDK)
    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present
    # Install Docker SDK for Python
    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        state: present
    # Run Portainer CE
    - name: Run Portainer CE container
      ansible.builtin.docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        restart_policy: always
        ports:
          - "9000:9000"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "portainer_data:/data"